In [2]:
 from sklearn.datasets import load_iris

iris = load_iris()

In [3]:
# print(iris)

In [4]:
print(iris.data)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [5]:
print(iris.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [6]:
print(iris.feature_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [7]:
print(iris.target_names)

['setosa' 'versicolor' 'virginica']


In [8]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [9]:
pd.DataFrame(data=iris.data, columns=iris.feature_names)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [10]:
df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
df.head(3)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2

In [11]:
df['label'] = iris.target
df.head(3)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   

   label  
0      0  
1      0  
2      0

In [12]:
# x,y >> train / test data 구분

x = iris.data
y = df['label']

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test =\
train_test_split(x, y, test_size=0.2, random_state=42)

In [13]:
x_train.shape, x_test.shape

((120, 4), (30, 4))

In [14]:
y_train.shape, y_test.shape

((120,), (30,))

In [15]:
# 머신러닝 알고리즘 선택 >> 모델링

# 의사결정나무 (DecissionTreeClassifier)

from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier()

# 훈련(반드시, 훈련용 데이터) >> 모델 구축
dt.fit(x_train, y_train)

DecisionTreeClassifier()

In [16]:
# 모델 성능평가(정확도 평가)

from sklearn.metrics import accuracy_score

# 예측 (평가용 데이터로 )
y_pred = dt.predict(x_test)
accuracy_score(y_test, y_pred)

1.0

라벨 인코딩 실습

In [17]:
from sklearn.preprocessing import LabelEncoder

items = ['TV','냉장고','전자렌지','컴퓨터', '아이패드', '모니터', '노트북']

# 1. 라벨인코더 모듈 불러오기
le = LabelEncoder()
# 2. 라벨인코더로 데이터(items) 훈련 >> 변환 (숫자로 인코딩)
le.fit(items)
labels = le.transform(items)
labels

array([0, 1, 5, 6, 4, 3, 2])

In [18]:
# 원상 복구 하고 싶어요
# decode

origin = le.inverse_transform(labels)
origin

array(['TV', '냉장고', '전자렌지', '컴퓨터', '아이패드', '모니터', '노트북'], dtype='<U4')

원-핫(One-Hot) 인코딩

In [19]:
from sklearn.preprocessing import OneHotEncoder

print(labels)

[0 1 5 6 4 3 2]


In [20]:
labels.reshape(-1, 1)

array([[0],
       [1],
       [5],
       [6],
       [4],
       [3],
       [2]])

In [21]:
labels_ = labels.reshape(-1, 1)

ohe = OneHotEncoder()
ohe.fit(labels_)
ohe_labels = ohe.transform(labels_)
ohe_labels

<7x7 sparse matrix of type '<class 'numpy.float64'>'
	with 7 stored elements in Compressed Sparse Row format>

In [22]:
ohe_labels.toarray()

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.]])

In [23]:
ohe_labels.shape

(7, 7)

In [24]:
# 판다스 활용, get_dummies()
# 더미변수 : 1,0 으로 코딩 가능한 변수
# 예) 호텔에 수영장 있으면 1, 없으면 0, 강/바다가 보이면 1, 아니면 0

In [25]:
import pandas as pd

temp_df = pd.DataFrame({'item':items})
temp_df

item
0    TV
1   냉장고
2  전자렌지
3   컴퓨터
4  아이패드
5   모니터
6   노트북

In [26]:
temp_df = pd.DataFrame({'item':labels})
temp_df

item
0     0
1     1
2     5
3     6
4     4
5     3
6     2

In [27]:
pd.get_dummies(temp_df)

item
0     0
1     1
2     5
3     6
4     4
5     3
6     2

Scaling (스케일링)

In [28]:
# 단위 통일 >> 단위로 1로 만드는 것(정규화) x / |x|

In [29]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     label  
0        0  
1        0  
2        0  
3        0  
4        0  
..     ...  
145      2  
146      2  
147      2  
148      2  
149      2  

[150 rows x 5 columns]

In [30]:
df.iloc[:, :-1]

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [31]:
df_features = df.iloc[:, :-1]

In [37]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

scaler = MinMaxScaler()
# scaler = StandardScaler()

scaler.fit(df_features)
df_scaled = scaler.transform(df_features)
df_scaled[:5]

array([[0.22222222, 0.625     , 0.06779661, 0.04166667],
       [0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [0.11111111, 0.5       , 0.05084746, 0.04166667],
       [0.08333333, 0.45833333, 0.08474576, 0.04166667],
       [0.19444444, 0.66666667, 0.06779661, 0.04166667]])

In [38]:
pd.DataFrame(data=df_scaled, columns=iris.feature_names)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0             0.222222          0.625000           0.067797          0.041667
1             0.166667          0.416667           0.067797          0.041667
2             0.111111          0.500000           0.050847          0.041667
3             0.083333          0.458333           0.084746          0.041667
4             0.194444          0.666667           0.067797          0.041667
..                 ...               ...                ...               ...
145           0.666667          0.416667           0.711864          0.916667
146           0.555556          0.208333           0.677966          0.750000
147           0.611111          0.416667           0.711864          0.791667
148           0.527778          0.583333           0.745763          0.916667
149           0.444444          0.416667           0.694915          0.708333

[150 rows x 4 columns]

In [39]:
df_scaled = pd.DataFrame(data=df_scaled, columns=iris.feature_names)
df_scaled.head(3)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0           0.222222          0.625000           0.067797          0.041667
1           0.166667          0.416667           0.067797          0.041667
2           0.111111          0.500000           0.050847          0.041667

In [40]:
print(df_scaled.mean()) # 평균
print()
print(df_scaled.var()) # 분산

sepal length (cm)    0.428704
sepal width (cm)     0.440556
petal length (cm)    0.467458
petal width (cm)     0.458056
dtype: float64

sepal length (cm)    0.052908
sepal width (cm)     0.032983
petal length (cm)    0.089522
petal width (cm)     0.100869
dtype: float64
