In [ ]:
import pandas as pd
import numpy as np

from sklearn import linear_model
from sklearn.metrics import mean_squared_error

from sklearn.model_selection import KFold

In [ ]:
# Ridge regression

reg = linear_model.Ridge(alpha = 1)
# alpha : tuning parameter (lambda 상수)

In [ ]:
# 훈련
reg.fit([[0,0],[0,0],[1,1]],[0,.1,1])
# x =[[0,0],[0,0],[1,1]]
# y = [0,.1,1]

Ridge(alpha=1)

In [ ]:
# test
pred_test = reg.predict([[0,1]])
pred_test

array([0.45714286])

In [ ]:
# coefficient
reg.coef_

array([0.27142857, 0.27142857])

Lasso 간단한 예제

In [ ]:
reg = linear_model.Lasso(alpha = 0.1)
#reg = linear_model.Lasso(alpha = 1)

In [ ]:
# 훈련
reg.fit([[0,0],[0,0],[1,1]],[0,.1,1])
# x =[[0,0],[0,0],[1,1]]
# y = [0,.1,1]

Lasso(alpha=0.1)

In [ ]:
# test
pred_test = reg.predict([[0,1]])
pred_test

array([0.2])

In [ ]:
# coefficient
reg.coef_

# 두 번째 reg의 coef_ 값은 0이다

array([0.5, 0. ])

Advertisting 데이터 활용 모델 선택

In [ ]:
ad = pd.read_csv('/content/drive/MyDrive/MLP_bigdata/data/Advertising.csv',index_col = 0)
ad.head()

TV  Radio  Newspaper  Sales
1  230.1   37.8       69.2   22.1
2   44.5   39.3       45.1   10.4
3   17.2   45.9       69.3    9.3
4  151.5   41.3       58.5   18.5
5  180.8   10.8       58.4   12.9

In [ ]:
# ad 데이터에 Lasso 적용 ==> 최적의 lambda 선정

n_fold = 5

for t_param in (0.001, 1 , 1000):
  # lambda 값 설정 0.001, 1 , 1000
  print( 'Lambda :',t_param)
  kf= KFold(n_splits = n_fold)
  idx =1

  sum_val_mse = 0
  for train, val in kf.split(ad):
    print('Fold: #', idx)

    # training set 의 feature와 response 분리
    train_x = ad.iloc[train][['TV','Radio','Newspaper']]
    train_y = ad.iloc[train][['Sales']]

    # test set 의 feature와 response 분리
    val_x = ad.iloc[val][['TV','Radio','Newspaper']]
    val_y = ad.iloc[val][['Sales']]

    # lasso 적용
    regr =linear_model.Lasso(alpha=t_param)

    # 훈련
    regr.fit(train_x[['TV','Radio','Newspaper']],train_y)

    #coef
    print('Coef :',regr.coef_)

    # validation set 예측
    val_y_pred = regr.predict(val_x[['TV','Radio','Newspaper']])

    # validation MSE
    val_mse = mean_squared_error(val_y, val_y_pred)

    sum_val_mse = val_mse

    print('--' * 100)
    idx +=1

  print('Average MSE :%.3f'% (sum_val_mse/n_fold))
  print('**'*100)

Lambda : 0.001
Fold: # 1
Coef : [0.04585753 0.18790125 0.00361145]
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Fold: # 2
Coef : [0.04513111 0.1879391  0.00140999]
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Fold: # 3
Coef : [ 0.04698029  0.18872464 -0.00235756]
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Fold: # 4
Coef : [ 0.04315907  0.20013028 -0.00758214]
------------------------------------------------------------------------------------------------------------------------------------------------------------------------