데이터 분석_titanic with chatgpt

In [2]:
# 재표본 추출 방법(resampling)

import numpy as np

from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

from sklearn.model_selection import KFold # k-fold cross validation
from sklearn.utils import resample        # boostrap

# 임의로 데이터 섞기 위해(random shuffling)
# -> 편향 방지를 위함

from sklearn. utils import shuffle

from sklearn.datasets import load_iris

K-Fold cross calidation

In [6]:
# 간단한 예제

x = ['a','b','c','d']

kf = KFold(n_splits=2) # 2개로 나누기

for train,test in kf.split(x):
  print("%s %s"%(train, test))
  print()
  print(x[train[0]],x[train[1]],x[test[0]],x[test[1]])

[2 3] [0 1]

c d a b
[0 1] [2 3]

a b c d


In [4]:
print(x[train[0]],x[train[1]])

a b


In [5]:
print(x[test[0]],x[test[1]])

c d


iris data 활용하여
KFold cross validation

In [7]:
x_iris,y_iris = load_iris(return_X_y= True)

In [8]:
x_iris[:10]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [9]:
y_iris

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [11]:
#  5 fold cross validation

kf = KFold(n_splits=5)
idx = 1

for train, val in kf.split(x_iris):
  print("Fold: #",idx)

  # k-fold 결과 확인
  print("%s %s"%(train,val))
  print()
  print(y_iris[train])
  print()
  print(y_iris[val])

  print('--'*100)
  idx += 1

Fold: # 1
[ 30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45  46  47
  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65
  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83
  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119
 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149] [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
----------------------------------------------------------------------------------------------------

In [12]:
#  5 fold cross validation

kf = KFold(n_splits=5)
idx = 1

for train, val in kf.split(x_iris):
  print("Fold: #",idx)

  # LDA 훈련
  lda = LinearDiscriminantAnalysis().fit(x_iris[train],y_iris[train])

  # 클래스 예측
  print("True label : ", y_iris[val])
  print("Pred label : ", lda.predict(x_iris[val]))

  # accuracy 정확도
  print('Accuracy : ',lda.score(x_iris[val],y_iris[val]))


  print('--'*100)
  idx += 1

Fold: # 1
True label :  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
Pred label :  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
Accuracy :  1.0
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Fold: # 2
True label :  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]
Pred label :  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]
Accuracy :  1.0
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Fold: # 3
True label :  [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
Pred label :  [1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 2 1 1 1 1 1 2 1 1 1 1 1 1]
Accuracy :  0.9
----------------------------------------------------------------

bootstrap 간단한 예제

In [13]:
x = np.array([[1.,0],[2.,1.],[0.,0.]])
y = np.array([0,1,2])

print(x)
print(y)

[[1. 0.]
 [2. 1.]
 [0. 0.]]
[0 1 2]


In [15]:
x,y = resample(x,y)
(x,y)

(array([[0., 0.],
        [0., 0.],
        [2., 1.]]),
 array([2, 2, 1]))

iris data(bootstrap)

In [17]:
x_iris,y_iris = load_iris(return_X_y=True)

In [18]:
x,y = resample(x_iris,y_iris)

In [21]:
print(x)
print()
print(y)

[[6.9 3.2 5.7 2.3]
 [7.9 3.8 6.4 2. ]
 [4.6 3.4 1.4 0.3]
 [5.1 3.3 1.7 0.5]
 [6.1 2.8 4.7 1.2]
 [5.1 3.7 1.5 0.4]
 [6.3 2.3 4.4 1.3]
 [6.1 3.  4.6 1.4]
 [5.8 2.7 4.1 1. ]
 [7.2 3.6 6.1 2.5]
 [7.1 3.  5.9 2.1]
 [5.2 3.4 1.4 0.2]
 [5.1 3.5 1.4 0.3]
 [7.7 3.  6.1 2.3]
 [5.6 2.9 3.6 1.3]
 [5.2 3.5 1.5 0.2]
 [5.5 2.4 3.7 1. ]
 [5.7 4.4 1.5 0.4]
 [6.  3.  4.8 1.8]
 [6.7 3.3 5.7 2.5]
 [6.  2.2 5.  1.5]
 [5.3 3.7 1.5 0.2]
 [5.5 4.2 1.4 0.2]
 [5.7 4.4 1.5 0.4]
 [4.4 3.2 1.3 0.2]
 [6.4 2.8 5.6 2.1]
 [6.  3.  4.8 1.8]
 [4.8 3.1 1.6 0.2]
 [6.4 3.2 4.5 1.5]
 [5.2 3.4 1.4 0.2]
 [5.8 2.8 5.1 2.4]
 [7.6 3.  6.6 2.1]
 [6.7 3.3 5.7 2.5]
 [4.7 3.2 1.6 0.2]
 [5.2 4.1 1.5 0.1]
 [6.1 3.  4.6 1.4]
 [4.9 2.4 3.3 1. ]
 [6.4 2.7 5.3 1.9]
 [6.7 3.1 4.4 1.4]
 [4.6 3.2 1.4 0.2]
 [5.9 3.  4.2 1.5]
 [6.9 3.1 5.4 2.1]
 [4.8 3.  1.4 0.3]
 [5.6 3.  4.1 1.3]
 [4.7 3.2 1.3 0.2]
 [5.6 2.5 3.9 1.1]
 [7.2 3.6 6.1 2.5]
 [5.6 3.  4.5 1.5]
 [5.1 3.8 1.5 0.3]
 [5.1 3.5 1.4 0.2]
 [6.4 2.8 5.6 2.2]
 [4.4 2.9 1.4 0.2]
 [6.5 2.8 4.

In [22]:
# unique 한 값 및 개수 출력
unique,counts = np.unique(y, return_counts=True)

In [23]:
unique

array([0, 1, 2])

In [24]:
counts

array([50, 53, 47])